portale/src/Entity/Clienti.php
<?php

namespace App\Entity;

use App\Repository\ClientiRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientiRepository::class)]
class Clienti
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $ragione_sociale = null;

    #[ORM\Column(length: 11)]
    private ?string $partita_iva = null;

    #[ORM\Column(length: 255)]
    private ?string $indirizzo = null;

    #[ORM\Column(length: 255)]
    private ?string $provincia = null;

    #[ORM\Column(length: 255)]
    private ?string $cap = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $pec = null;

    #[ORM\Column(length: 20)]
    private ?string $telefono = null;

    #[ORM\Column(length: 255)]
    private ?string $settore_attivita = null;

    #[ORM\Column(nullable: true)]
    private ?int $id_agente = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $data_acquisizione = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $deleted_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRagioneSociale(): ?string
    {
        return $this->ragione_sociale;
    }

    public function setRagioneSociale(string $ragione_sociale): static
    {
        $this->ragione_sociale = $ragione_sociale;

        return $this;
    }

    public function getPartitaIVA(): ?string
    {
        return $this->partita_iva;
    }

    public function setPartitaIVA(string $partita_IVA): static
    {
        $this->partita_iva   = $partita_IVA;

        return $this;
    }

    public function getIndirizzo(): ?string
    {
        return $this->indirizzo;
    }

    public function setIndirizzo(string $indirizzo): static
    {
        $this->indirizzo = $indirizzo;

        return $this;
    }

    public function getProvincia(): ?string
    {
        return $this->provincia;
    }

    public function setProvincia(string $provincia): static
    {
        $this->provincia = $provincia;

        return $this;
    }

    public function getCap(): ?string
    {
        return $this->cap;
    }

    public function setCap(string $cap): static
    {
        $this->cap = $cap;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPec(): ?string
    {
        return $this->pec;
    }

    public function setPec(string $pec): static
    {
        $this->pec = $pec;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): static
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getSettoreAttivita(): ?string
    {
        return $this->settore_attivita;
    }

    public function setSettoreAttivita(string $settore_attivita): static
    {
        $this->settore_attivita = $settore_attivita;

        return $this;
    }

    public function getIdAgente(): ?int
    {
        return $this->id_agente;
    }

    public function setIdAgente(?int $id_agente): static
    {
        $this->id_agente = $id_agente;

        return $this;
    }

    public function getDataAcquisizione(): ?\DateTimeInterface
    {
        return $this->data_acquisizione;
    }

    public function setDataAcquisizione(\DateTimeInterface $data_acquisizione): static
    {
        $this->data_acquisizione = $data_acquisizione;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeInterface $deleted_at): static
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }
}

portale/src/Controller/route/ClientiController.php
<?php

namespace App\Controller\route;

use App\Entity\Clienti;
use App\Helper\Formatter;
use App\Helper\SessionHandler;
use App\Repository\ClientiRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ClientiController extends AbstractController
{
    private EntityManagerInterface $em;

    public function __construct(EntityManagerInterface $em){
        $this->em = $em;
    }


    #[Route('/clienti', name: 'mostra_clienti')]
    public function getClientiWithAgents (ClientiRepository $clientiRepository) : Response
    {
        SessionHandler::controlSession();

        $clienti = $clientiRepository->findClientsWithAgent();

        foreach ($clienti as $key => $value) {
            Formatter::underscoreToCamelCaseFilter($key);
        }

        return $this->render('clienti/clienti.html.twig', ['clienti' => $clienti]);
    }

    #[Route('/clienti/create', name: 'nuovo_cliente')]
    public function createClient(Request $request)
    {
        SessionHandler::controlSession();
        return $this->render("clienti/create.html.twig");
    }

    #[Route('/clienti/edit/{id}', name: 'modifica_cliente')]
    public function editClient(int|string $id, ClientiRepository $clientiRepository, Request $request): Response
    {
        SessionHandler::controlSession();

        $cliente = $clientiRepository->findOneBy(['id' => $id]);

        if (!$cliente) {
            throw $this->createNotFoundException('Cliente non trovato');
        }


        return $this->render('clienti/edit.html.twig', ['cliente' => $cliente]);
    }


}

portale/templates/clienti/clienti.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Clienti</h1>

    <div class="content mb-4">
        <div id="table-container" class="col-12">
            <table id="table-row" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th id="th-1 d-none"></th>
                    <th id="th-2">Ragione Sociale</th>
                    <th id="th-3">Partita IVA</th>
                    <th id="th-4">Indirizzo</th>
                    <th id="th-5">Provincia</th>
                    <th id="th-6">CAP</th>
                    <th id="th-7">Email</th>
                    <th id="th-8">PEC</th>
                    <th id="th-9">Telefono</th>
                    <th id="th-10">Settore</th>
                    <th id="th-11">Agente</th>
                    <th id="th-12">Data Acquisizione</th>
                    <th id="th-13"></th>
                </tr>
                </thead>
                <tbody>
                {% for element in clienti %}
                    <tr data-id="{{ element[0].id }}">
                        <td></td>
                        <td>{{ element[0].ragioneSociale }}</td>
                        <td>{{ element[0].partitaIVA }}</td>
                        <td>{{ element[0].indirizzo }}</td>
                        <td>{{ element[0].provincia }}</td>
                        <td>{{ element[0].cap }}</td>
                        <td>{{ element[0].email }}</td>
                        <td>{{ element[0].pec }}</td>
                        <td>{{ element[0].telefono }}</td>
                        <td>{{ element[0].settoreAttivita }}</td>
                        <td>{{ element.agente }}</td>
                        <td>{{ element[0].dataAcquisizione|date('Y-m-d') }}</td>
                        <td>
                            <div class="button-container">
                                <button id="btn-edit" class="btn btn-primary edit-row">
                                    <i class="bi bi-pencil"></i>
                                </button>
                                <button id="btn-remove" class="btn btn-danger remove-row">
                                    <i class="bi bi-trash"></i>
                                </button>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                </tfoot>
            </table>
        </div>
    </div>
        <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
        <script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
    <script>
        $(function () {
            var table = $('#table-row').DataTable({
                language: {
                    "url": "/js/Italian.json"                },
                ordering: true,
                columns: [
                    {"orderable": false},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": true},
                    {"orderable": false}
                ],
                order: [[0, 'asc']],
                scrollX: true,
                pagingType: 'simple_numbers',
                initComplete: function() {
                    let search = $('.dt-search');
                    search.parent().removeClass().addClass('col-md-6 d-flex justify-content-end align-items-center');
                    search.addClass('col-6 me-2');
                    search.after(  `<div class="col-auto text-right pe-0">
                                        <button id="btn-add" class="btn btn-primary btn-sm "><a id="add_persone" href="{{ path('nuovo_cliente') }}"> Aggiungi Cliente</a></button>
                                    </div>`
                    );


                }
            })

            table
                .on('order.dt search.dt', function () {
                    var i = 1;
                    table
                        .cells(null, 0, { search: 'applied', order: 'applied' })
                        .every(function (cell) {
                            this.data(i++);
                        });
                })
                .draw();

            user.init();
        })

        let user = {
            init: function (){
                user.setOnClickButton();
                user.updateIndexes();
            },

            setOnClickButton: function () {
                $('.remove-row').off('click').on('click', function () {
                    if (confirm("Sei sicuro di voler eliminare questo cliente?")) {
                        user.removeRow($(this).closest('tr'));
                    }
                })

                $('.edit-row').off('click').on('click', function () {
                    var rowId = $(this).closest('tr').data('id');
                    console.log('ID della riga:', rowId);

                    const baseUrl = "http://localhost:8080/clienti/edit/";
                    window.location.href = `${baseUrl}${rowId}`;
                });

            },

            removeRow: function (row){
                let id = row.data('id');
                $.ajax({
                    url:    'http://localhost:8080/api/clients/' + id,
                    type:   'DELETE',
                    dataType: 'json',
                    data: {id: id},

                    success: function(data) {
                        if (data.ok) {
                            console.log(data.message);
                            row.remove();
                            user.updateIndexes();
                        } else {
                            console.error('Errore:', data.error);
                        }
                    },

                    error: function(xhr, status, error) {
                        console.error('AJAX Error:', xhr.responseText);
                        console.error('Status:', status);
                        console.error('Error:', error);
                    }
                })
            },

            updateIndexes: function () {
                let rows = $('tbody tr');
                rows.each(function (index) {
                    $(this).find('td').first().text(index + 1);
                });
            }


        }
    </script>
{% endblock %}

portale/templates/clienti/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div id="intestazione">
        <h1>Nuovo Cliente</h1>
        <h6>Compilare il form seguente per aggiungere un nuovo cliente</h6>
    </div>

    <div class="container">
        <form id="formDati" method="post">
            <div class="form-group row">
                <div class="col-md-4 mt-3">
                    <input type="text" class="form-control" id="ragione-sociale" name="ragione_sociale" placeholder="Ragione Sociale">
                </div>
                <div class="col-md-4 mt-3">
                    <input type="text" class="form-control" id="partita-iva" name="partita_iva" placeholder="Partita IVA">
                </div>
                <div class="col-md-4 mt-3">
                    <input type="text" class="form-control" id="settore-attivita" name="settore_attivita" placeholder="Settore Attività">
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-3 mt-3">
                    <input type="text" class="form-control" id="indirizzo" name="indirizzo" placeholder="Indirizzo">
                </div>
                <div class="col-md-3 mt-3">
                    <input type="text" class="form-control" id="cap" name="cap" placeholder="CAP">
                </div>
                <div class="col-md-3 mt-3">
                    <input type="text" class="form-control" id="comune" name="comune" placeholder="Comune" readonly>
                </div>
                <div class="col-md-3 mt-3">
                    <input type="text" class="form-control" id="provincia" name="provincia" placeholder="Provincia" readonly>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-md-4 mt-3">
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                </div>
                <div class="col-md-4 mt-3">
                    <input type="email" class="form-control" id="pec" name="pec" placeholder="PEC">
                </div>
                <div class="col-md-4 mt-3">
                    <input type="tel" class="form-control" id="telefono" name="telefono" placeholder="Telefono">
                </div>
            </div>


            <div class="form-group row">
                <div class="col-md-6 mt-3">
                    <select class="form-control" id="agente-assegnato" name="id_agente">
                        <option>Seleziona un agente</option>
                    </select>
                </div>
                <div class="col-md-6 mt-3">
                    <input type="date" class="form-control" id="data-acquisizione" name="data_acquisizione">
                </div>
            </div>

            <div class="col-md-12 mt-4 mb-5">
                <input type="button" id="save" class="btn btn-success btn-block w-100"
                       value="Salva">
            </div>
        </form>
    </div>

    <script>
        $(function () {
            $.validator.addMethod("phoneIT", function(value, element) {
                return this.optional(element) || /^(\+39)?\d{1,10}$/.test(value);
            }, "Per favore, inserisci un numero di telefono valido.");

            $("#formDati").validate({
                rules: {
                    ragione_sociale: {
                        required: true,
                        minlength: 2
                    },
                    partita_iva: {
                        required: true,
                        minlength: 11,
                        maxlength: 11
                    },
                    settore_attivita: {
                        required: true,
                        minlength: 2
                    },
                    indirizzo: {
                        required: true,
                        minlength: 5
                    },
                    cap: {
                        required: true,
                        minlength: 5,
                        maxlength: 5,
                        digits: true
                    },
                    comune: {
                        required: true,
                    },
                    provincia: {
                        required: true,
                        minlength: 2
                    },
                    email: {
                        required: true,
                        email: true
                    },
                    pec: {
                        required: true,
                        email: true
                    },
                    telefono: {
                        required: true,
                        phoneIT: true
                    },
                    id_agente: {
                        required: true
                    },
                    data_acquisizione: {
                        required: true,
                        date: true
                    }
                },
                messages: {
                    ragione_sociale: {
                        required: "Inserisci la ragione sociale.",
                        minlength: "La ragione sociale deve essere lunga almeno 2 caratteri."
                    },
                    partita_iva: {
                        required: "Inserisci la partita IVA.",
                        minlength: "La partita IVA deve essere lunga 11 caratteri.",
                        maxlength: "La partita IVA deve essere lunga 11 caratteri."
                    },
                    settore_attivita: {
                        required: "Inserisci il settore di attività.",
                        minlength: "Il settore di attività deve essere lungo almeno 2 caratteri."
                    },
                    indirizzo: {
                        required: "Inserisci l'indirizzo.",
                        minlength: "L'indirizzo deve essere lungo almeno 5 caratteri."
                    },
                    cap: {
                        required: "Inserisci il CAP.",
                        minlength: "Il CAP deve essere lungo 5 caratteri.",
                        maxlength: "Il CAP deve essere lungo 5 caratteri.",
                        digits: "Il CAP deve contenere solo cifre."
                    },
                    comune: {
                        required: "Inserisci il comune."
                    },
                    provincia: {
                        required: "Inserisci la provincia.",
                        minlength: "La provincia deve essere lunga almeno 2 caratteri."
                    },
                    email: {
                        required: "Inserisci l'email.",
                        email: "Inserisci un'email valida."
                    },
                    pec: {
                        required: "Inserisci la PEC.",
                        email: "Inserisci una PEC valida."
                    },
                    telefono: {
                        required: "Inserisci il numero di telefono.",
                        phoneIT: "Per favore, inserisci un numero di telefono valido."
                    },
                    id_agente: {
                        required: "Seleziona un agente."
                    },
                    data_acquisizione: {
                        required: "Inserisci la data di acquisizione.",
                        date: "Inserisci una data valida."
                    }
                },
                highlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
                    $(element).closest('.form-control').removeClass('border-success').addClass('border-danger');
                },
                unhighlight: function(element) {
                    $(element).closest('.form-group').removeClass('has-error').addClass('has-success');
                    $(element).closest('.form-control').removeClass('border-danger').addClass('border-success');
                }
            });
            user.init();
        })

        let user = {
            init: function (){
                user.setOnClickButton();
            },

            setOnClickButton: function (){
                $('#cap').on('change', function (){
                    let inputCap = $('#cap').val();
                    console.log('CAP:', inputCap);
                    user.getAgentsByCap(inputCap);
                    user.getComuneProvinciaByCap(inputCap);
                })

                $('#save').on('click', function (){
                   user.saveNewCustomer();
                })
            },

            getAgentsByCap: function (inputCap){
                $.ajax({
                    url: 'http://localhost:8080/api/agentsCap/agentsByCap/' + inputCap,
                    type: 'GET',
                    dataType: 'json',

                    success: function (data) {
                        if(data.ok) {
                            console.log(data.ok, data.message, data.data);
                            let agentSelect = $('#agente-assegnato');
                            agentSelect.empty();
                            agentSelect.append('<option>Seleziona un agente</option>');

                            $.each(data.data, function (index, agente) {
                                let option = $('<option></option>').attr('value', agente.id).text(agente.nome + ' ' + agente.cognome);
                                agentSelect.append(option);
                            });
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error('AJAX Error:', xhr.responseText);
                        console.error('Status:', status);
                        console.error('Error:', error);
                    }
                })

            },

            getComuneProvinciaByCap: function (inputCap){
                $.ajax({
                    url: 'http://localhost:8080/api/cap/comuneProviciaByCap/' + inputCap,
                    type: 'GET',
                    dataType: 'json',

                    success: function (response) {
                        const data = response.data[0];
                        if(response.ok) {
                            // console.log(response.ok, response.message, response.data);
                            $('#comune').val(data['comune']);
                            $('#provincia').val(data['provincia']);
                        }
                    },
                    error: function (xhr, status, error) {
                        let errorJson = JSON.parse(xhr.responseText);
                        console.error('AJAX Error:', xhr.responseText);
                        console.error('Status:', status);
                        console.error('Error:', error);
                        if (errorJson.error === "CAP non trovato"){
                            alert(errorJson.error);
                            $('#cap').closest('.form-group').addClass('has-error');
                            $('#cap').addClass('border-danger');
                        }
                    }
                })
            },

            saveNewCustomer: function (){
                let formData = new FormData($("#formDati")[0]);
                let formDataObj = {};

                formData.forEach((value, key) => {
                    formDataObj[key] = value;
                });

                $.ajax({
                    url: 'http://localhost:8080/api/clients',
                    cache: false,
                    contentType: 'application/json',
                    processData: false,
                    data: JSON.stringify(formDataObj),
                    type: 'POST',
                    success: function (data) {
                        console.log(data)
                        if (data.ok === true) {
                            let successAlert = `<div class="alert alert-success d-flex align-items-center mt-3 mb-3" role="alert">
                                                    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                                                    <div>
                                                        Creazione cliente avvenuta con successo!
                                                    </div>
                                                </div>`;

                            let form = $('#formDati')
                            form.before(successAlert);
                            form.remove();
                            $('#intestazione').remove();

                            setTimeout(function() {
                                window.location.pathname = '/clienti';
                            }, 1700);
                        }
                    },
                    error: function (xhr, status, error) {
                        let errorJson = JSON.parse(xhr.responseText);
                        console.error('AJAX Error:', xhr.responseText);
                        console.error('Status:', status);
                        console.error('Error:', error);
                        if (errorJson.userMessage === "Scegliere un agente da assegnare"){
                            alert(errorJson.userMessage);
                            $('#agente-assegnato').closest('.form-group').addClass('has-error');
                            $('#agente-assegnato').addClass('border-danger');
                        } else {
                            alert(errorJson.userMessage);
                        }
                    }
                })
            }
        }
    </script>
{% endblock %}